language: node_js
node_js: node

before_script:
  - npm install

script: 
  - npm test

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    branch: master
    tags: true
    condition: "$TRAVIS_TAG =~ ^(v\\d\\.\\d\\.\\d)(-\\w+)?$"
